CREATE TABLE IF NOT EXISTS nfe_issuer (
    cnpj VARCHAR(14) PRIMARY KEY,
    razao_social VARCHAR(255) NOT NULL,
    nome_fantasia VARCHAR(255),
    ie VARCHAR(20),
    im VARCHAR(20),
    crt VARCHAR(1) NOT NULL,
    fone VARCHAR(20),
    logradouro VARCHAR(255) NOT NULL,
    numero VARCHAR(255) NOT NULL,
    bairro VARCHAR(255) NOT NULL,
    municipio_codigo VARCHAR(255) NOT NULL,
    municipio_nome VARCHAR(255) NOT NULL,
    uf VARCHAR(2) NOT NULL,
    cep VARCHAR(8) NOT NULL,
    pais_codigo VARCHAR(255) NOT NULL,
    pais_nome VARCHAR(255) NOT NULL,
    certificate_path VARCHAR(500),
    encrypted_password VARCHAR(500),
    certificate_tipo VARCHAR(10),
    active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL
);
